title: “FAKE SPECIALIST” YAN LIMENG
description: >-
  Overnight, Yan Limeng has caused a sensation throughout the right wing media.
  The senior adviser of President Trump and conservatives who has authority seem
  her as a hero. The social media labelled her interview as a fake news just as
  quickly. Scientists 
template:
  repo: '"fake-specialist"-yan-limeng-template'
  name: '"fake-specialist"-yan-limeng'
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
